# Generated by Django 5.2.4 on 2025-07-05 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_event_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='tickets',
            field=models.PositiveIntegerField(default=0, help_text='Total number of tickets for the event'),
        ),
    ]
